# Generated by Django 4.1.5 on 2023-01-15 09:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('enterprise_name', models.CharField(max_length=200, unique=True)),
                ('email', models.EmailField(max_length=254, verbose_name='Email address')),
                ('date', models.DateTimeField(default=datetime.datetime(2023, 1, 15, 9, 12, 59, 140098, tzinfo=datetime.timezone.utc))),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
