# Generated by Django 4.1.5 on 2023-02-26 14:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
