# Generated by Django 4.1.5 on 2023-03-12 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_franchisemanager_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='franchisemanager',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mainmanager',
            name='is_admin',
            field=models.BooleanField(default=True),
        ),
    ]
