# Generated by Django 4.1.5 on 2023-03-12 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_franchisemanager_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='franchisemanager',
            old_name='user',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='franchisemanager',
            old_name='First_name',
            new_name='first_name',
        ),
    ]
