# Generated by Django 4.0.3 on 2023-03-12 22:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_user_franchisemanager_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='franchisemanager',
            name='id',
        ),
        migrations.AddField(
            model_name='franchisemanager',
            name='branch',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='franchisemanager',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('item', models.CharField(max_length=50)),
                ('unit_price', models.IntegerField(default=0)),
                ('product_code', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('stock', models.IntegerField(default=0)),
                ('sold', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.productcategories')),
            ],
        ),
    ]
