# Generated by Django 4.0.3 on 2023-03-12 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_productcategories_remove_franchisemanager_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='category',
        ),
        migrations.DeleteModel(
            name='ProductCategories',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
